// import fs from 'fs';
// import path from 'path';
// import { Country } from '../types';
// import logger from '../common/utils/logger';


// export class ImageGeneratorService {
//   private cacheDir: string;

//   constructor() {
//     this.cacheDir = path.join(process.cwd(), 'cache');
//     this.ensureCacheDirectory();
//   }

//   private ensureCacheDirectory(): void {
//     if (!fs.existsSync(this.cacheDir)) {
//       fs.mkdirSync(this.cacheDir, { recursive: true });
//       logger.info('Created cache directory');
//     }
//   }

//   async generateSummaryImage(
//     totalCountries: number,
//     topCountries: Country[],
//     lastRefreshedAt: Date
//   ): Promise<string> {
//     try {
//       logger.info('Generating summary image...');

//       // Create a simple HTML file that can be converted to image
//       const htmlContent = this.generateHTMLContent(
//         totalCountries,
//         topCountries,
//         lastRefreshedAt
//       );
//       const htmlPath = path.join(this.cacheDir, 'summary.html');
//       fs.writeFileSync(htmlPath, htmlContent);

//       // Create a simple text-based summary as fallback
//       const textContent = this.generateTextContent(
//         totalCountries,
//         topCountries,
//         lastRefreshedAt
//       );
//       const textPath = path.join(this.cacheDir, 'summary.txt');
//       fs.writeFileSync(textPath, textContent);

//       // For now, we'll use the HTML file as our "image"
//       const imagePath = path.join(this.cacheDir, 'summary.png');

//       // Create a simple placeholder PNG file (1x1 pixel transparent PNG)
//       const placeholderPng = Buffer.from([
//         0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a, 0x00, 0x00, 0x00, 0x0d,
//         0x49, 0x48, 0x44, 0x52, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x01,
//         0x08, 0x06, 0x00, 0x00, 0x00, 0x1f, 0x15, 0xc4, 0x89, 0x00, 0x00, 0x00,
//         0x0a, 0x49, 0x44, 0x41, 0x54, 0x78, 0x9c, 0x63, 0x00, 0x01, 0x00, 0x00,
//         0x05, 0x00, 0x01, 0x0d, 0x0a, 0x2d, 0xb4, 0x00, 0x00, 0x00, 0x00, 0x49,
//         0x45, 0x4e, 0x44, 0xae, 0x42, 0x60, 0x82,
//       ]);
//       fs.writeFileSync(imagePath, placeholderPng);

//       logger.info(`Summary files generated successfully: ${imagePath}`);
//       return imagePath;
//     } catch (error) {
//       logger.error('Error generating summary image:', error);
//       throw new Error('Failed to generate summary image');
//     }
//   }

//   private generateHTMLContent(
//     totalCountries: number,
//     topCountries: Country[],
//     lastRefreshedAt: Date
//   ): string {
//     return `
// <!DOCTYPE html>
// <html>
// <head>
//     <title>Country Currency Exchange API - Summary</title>
//     <style>
//         body { font-family: Arial, sans-serif; margin: 20px; background: #f8f9fa; }
//         .container { max-width: 800px; margin: 0 auto; background: white; padding: 20px; border-radius: 8px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
//         h1 { color: #2c3e50; text-align: center; }
//         h2 { color: #7f8c8d; text-align: center; }
//         .stats { background: #3498db; color: white; padding: 15px; border-radius: 5px; margin: 20px 0; }
//         .country-list { background: #ecf0f1; padding: 15px; border-radius: 5px; }
//         .country-item { padding: 8px 0; border-bottom: 1px solid #bdc3c7; }
//         .country-item:last-child { border-bottom: none; }
//         .footer { text-align: center; color: #7f8c8d; margin-top: 30px; font-size: 14px; }
//     </style>
// </head>
// <body>
//     <div class="container">
//         <h1>Country Currency Exchange API</h1>
//         <h2>Summary Report</h2>
        
//         <div class="stats">
//             <strong>Total Countries:</strong> ${totalCountries}<br>
//             <strong>Last Refreshed:</strong> ${lastRefreshedAt.toLocaleString()}
//         </div>
        
//         <h3>Top 5 Countries by Estimated GDP:</h3>
//         <div class="country-list">
//             ${topCountries
//               .map((country, index) => {
//                 const gdp = country.estimated_gdp
//                   ? `$${(country.estimated_gdp / 1e9).toFixed(2)}B`
//                   : 'N/A';
//                 return `<div class="country-item">${index + 1}. ${
//                   country.name
//                 } - ${gdp}</div>`;
//               })
//               .join('')}
//         </div>
        
//         <div class="footer">
//             Generated by Country Currency Exchange API
//         </div>
//     </div>
// </body>
// </html>`;
//   }

//   private generateTextContent(
//     totalCountries: number,
//     topCountries: Country[],
//     lastRefreshedAt: Date
//   ): string {
//     let content = `Country Currency Exchange API - Summary Report\n`;
//     content += `==============================================\n\n`;
//     content += `Total Countries: ${totalCountries}\n`;
//     content += `Last Refreshed: ${lastRefreshedAt.toLocaleString()}\n\n`;
//     content += `Top 5 Countries by Estimated GDP:\n`;
//     content += `--------------------------------\n`;

//     topCountries.forEach((country, index) => {
//       const gdp = country.estimated_gdp
//         ? `$${(country.estimated_gdp / 1e9).toFixed(2)}B`
//         : 'N/A';
//       content += `${index + 1}. ${country.name} - ${gdp}\n`;
//     });

//     content += `\nGenerated by Country Currency Exchange API\n`;
//     return content;
//   }

//   getSummaryImagePath(): string {
//     return path.join(this.cacheDir, 'summary.png');
//   }

//   summaryImageExists(): boolean {
//     const imagePath = this.getSummaryImagePath();
//     return fs.existsSync(imagePath);
//   }

//   deleteSummaryImage(): void {
//     const imagePath = this.getSummaryImagePath();
//     if (fs.existsSync(imagePath)) {
//       fs.unlinkSync(imagePath);
//       logger.info('Summary image deleted');
//     }
//   }
// }

// export default new ImageGeneratorService();


import fs from 'fs';
import path from 'path';
import puppeteer from 'puppeteer';
import { Country } from '../types';
import logger from '../common/utils/logger';

export class ImageGeneratorService {
  private cacheDir: string;

  constructor() {
    this.cacheDir = process.env.CACHE_DIR || path.join(process.cwd(), 'cache');
    this.ensureCacheDirectory();
  }

  private ensureCacheDirectory(): void {
    try {
      if (!fs.existsSync(this.cacheDir)) {
        fs.mkdirSync(this.cacheDir, { recursive: true });
        logger.info(`Created cache directory at ${this.cacheDir}`);
      } else {
        logger.info(`Cache directory exists: ${this.cacheDir}`);
      }
    } catch (error) {
      logger.error(`Failed to ensure cache dir ${this.cacheDir}:`, error);
      throw error;
    }
  }

  private generateHTMLContent(
    totalCountries: number,
    topCountries: Country[],
    lastRefreshedAt: Date
  ): string {
    return `
<!DOCTYPE html>
<html>
<head>
    <title>Country Currency Exchange API - Summary</title>
    <style>
        body { 
            font-family: Arial, sans-serif; 
            margin: 20px; 
            background: #f8f9fa; 
            padding: 0;
            margin: 0;
        }
        .container { 
            max-width: 800px; 
            margin: 0 auto; 
            background: white; 
            padding: 20px; 
            border-radius: 8px; 
            box-shadow: 0 2px 10px rgba(0,0,0,0.1); 
        }
        h1 { 
            color: #2c3e50; 
            text-align: center; 
        }
        h2 { 
            color: #7f8c8d; 
            text-align: center; 
        }
        .stats { 
            background: #3498db; 
            color: white; 
            padding: 15px; 
            border-radius: 5px; 
            margin: 20px 0; 
            text-align: center;
        }
        .country-list { 
            background: #ecf0f1; 
            padding: 15px; 
            border-radius: 5px; 
        }
        .country-item { 
            padding: 8px 0; 
            border-bottom: 1px solid #bdc3c7; 
        }
        .country-item:last-child { 
            border-bottom: none; 
        }
        .footer { 
            text-align: center; 
            color: #7f8c8d; 
            margin-top: 30px; 
            font-size: 14px; 
        }
        @media print { body { -webkit-print-color-adjust: exact; } } /* Ensure colors print */
    </style>
</head>
<body>
    <div class="container">
        <h1>Country Currency Exchange API</h1>
        <h2>Summary Report</h2>
        
        <div class="stats">
            <strong>Total Countries:</strong> ${totalCountries}<br>
            <strong>Last Refreshed:</strong> ${lastRefreshedAt.toLocaleString()}
        </div>
        
        <h3>Top 5 Countries by Estimated GDP:</h3>
        <div class="country-list">
            ${
              topCountries.length > 0
                ? topCountries
                    .map((country, index) => {
                      const gdp = country.estimated_gdp
                        ? `$${(country.estimated_gdp / 1e9).toFixed(2)}B`
                        : 'N/A';
                      return `<div class="country-item">${index + 1}. ${
                        country.name
                      } - ${gdp}</div>`;
                    })
                    .join('')
                : '<div class="country-item">No GDP data available</div>'
            }
        </div>
        
        <div class="footer">
            Generated by Country Currency Exchange API
        </div>
    </div>
</body>
</html>`;
  }

  async generateSummaryImage(
    totalCountries: number,
    topCountries: Country[],
    lastRefreshedAt: Date
  ): Promise<string> {
    const imagePath = path.join(this.cacheDir, 'summary.png');
    const htmlPath = path.join(this.cacheDir, 'temp_summary.html'); // Temp for content

    let browser: any = null;
    try {
      logger.info(
        'Starting puppeteer image gen: totalCountries=',
        totalCountries,
        'topCountries.length=',
        topCountries.length
      );

      // Step 1: Generate & write HTML
      logger.info('Generating HTML...');
      const htmlContent = this.generateHTMLContent(
        totalCountries,
        topCountries,
        lastRefreshedAt
      );
      fs.writeFileSync(htmlPath, htmlContent);
      logger.info('HTML written to temp file');

      // Step 2: Launch browser
      logger.info('Launching puppeteer...');
      browser = await puppeteer.launch({
        headless: true, // Fixed: Use 'true' for legacy mode (avoids TS error); upgrade types for 'new'
        args: [
          '--no-sandbox',
          '--disable-setuid-sandbox',
          '--disable-dev-shm-usage',
        ], // For stability
      });
      const page = await browser.newPage();
      logger.info('Browser launched');

      // Step 3: Set content & screenshot
      logger.info('Loading HTML and screenshot...');
      await page.setContent(htmlContent, { waitUntil: 'networkidle0' }); // Use string directly (no file load)
      await page.setViewport({ width: 800, height: 600 }); // Fixed size
      await page.screenshot({ path: imagePath, fullPage: false, type: 'png' });
      logger.info('Screenshot saved');

      // Step 4: Verify
      if (!fs.existsSync(imagePath)) {
        throw new Error(`PNG not found after screenshot at ${imagePath}`);
      }
      const stats = fs.statSync(imagePath);
      logger.info(
        `Summary PNG generated via puppeteer: ${imagePath} (size: ${stats.size} bytes)`
      );

      return imagePath;
    } catch (error: any) {
      logger.error('Error in generateSummaryImage (puppeteer):', {
        message: error.message,
        stack: error.stack,
        imagePath,
        totalCountries,
        topCountriesLength: topCountries?.length || 0,
      });
      // Cleanup
      if (fs.existsSync(imagePath)) fs.unlinkSync(imagePath);
      if (fs.existsSync(htmlPath)) fs.unlinkSync(htmlPath);
      if (browser) await browser.close();
      throw new Error(`Failed to generate summary image: ${error.message}`);
    } finally {
      if (browser) {
        await browser.close();
        logger.info('Browser closed');
      }
      // Always clean temp HTML
      if (fs.existsSync(htmlPath)) fs.unlinkSync(htmlPath);
    }
  }

  getSummaryImagePath(): string {
    return path.join(this.cacheDir, 'summary.png');
  }

  summaryImageExists(): boolean {
    const imagePath = this.getSummaryImagePath();
    const exists = fs.existsSync(imagePath);
    logger.info(`Checking image exists at ${imagePath}: ${exists}`);
    return exists;
  }

  deleteSummaryImage(): void {
    const imagePath = this.getSummaryImagePath();
    if (fs.existsSync(imagePath)) {
      fs.unlinkSync(imagePath);
      logger.info('Summary image deleted');
    }
  }
}

export default new ImageGeneratorService();
