import fs from 'fs';
import path from 'path';
import { Country } from '../types';
import logger from '../common/utils/logger';

export class ImageGeneratorService {
  private cacheDir: string;

  constructor() {
    this.cacheDir = path.join(process.cwd(), 'cache');
    this.ensureCacheDirectory();
  }

  private ensureCacheDirectory(): void {
    if (!fs.existsSync(this.cacheDir)) {
      fs.mkdirSync(this.cacheDir, { recursive: true });
      logger.info('Created cache directory');
    }
  }

  async generateSummaryImage(
    totalCountries: number,
    topCountries: Country[],
    lastRefreshedAt: Date
  ): Promise<string> {
    try {
      logger.info('Generating summary image...');

      // Create a simple HTML file that can be converted to image
      const htmlContent = this.generateHTMLContent(
        totalCountries,
        topCountries,
        lastRefreshedAt
      );
      const htmlPath = path.join(this.cacheDir, 'summary.html');
      fs.writeFileSync(htmlPath, htmlContent);

      // Create a simple text-based summary as fallback
      const textContent = this.generateTextContent(
        totalCountries,
        topCountries,
        lastRefreshedAt
      );
      const textPath = path.join(this.cacheDir, 'summary.txt');
      fs.writeFileSync(textPath, textContent);

      // For now, we'll use the HTML file as our "image"
      const imagePath = path.join(this.cacheDir, 'summary.png');

      // Create a simple placeholder PNG file (1x1 pixel transparent PNG)
      const placeholderPng = Buffer.from([
        0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a, 0x00, 0x00, 0x00, 0x0d,
        0x49, 0x48, 0x44, 0x52, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x01,
        0x08, 0x06, 0x00, 0x00, 0x00, 0x1f, 0x15, 0xc4, 0x89, 0x00, 0x00, 0x00,
        0x0a, 0x49, 0x44, 0x41, 0x54, 0x78, 0x9c, 0x63, 0x00, 0x01, 0x00, 0x00,
        0x05, 0x00, 0x01, 0x0d, 0x0a, 0x2d, 0xb4, 0x00, 0x00, 0x00, 0x00, 0x49,
        0x45, 0x4e, 0x44, 0xae, 0x42, 0x60, 0x82,
      ]);
      fs.writeFileSync(imagePath, placeholderPng);

      logger.info(`Summary files generated successfully: ${imagePath}`);
      return imagePath;
    } catch (error) {
      logger.error('Error generating summary image:', error);
      throw new Error('Failed to generate summary image');
    }
  }

  private generateHTMLContent(
    totalCountries: number,
    topCountries: Country[],
    lastRefreshedAt: Date
  ): string {
    return `
<!DOCTYPE html>
<html>
<head>
    <title>Country Currency Exchange API - Summary</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 20px; background: #f8f9fa; }
        .container { max-width: 800px; margin: 0 auto; background: white; padding: 20px; border-radius: 8px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
        h1 { color: #2c3e50; text-align: center; }
        h2 { color: #7f8c8d; text-align: center; }
        .stats { background: #3498db; color: white; padding: 15px; border-radius: 5px; margin: 20px 0; }
        .country-list { background: #ecf0f1; padding: 15px; border-radius: 5px; }
        .country-item { padding: 8px 0; border-bottom: 1px solid #bdc3c7; }
        .country-item:last-child { border-bottom: none; }
        .footer { text-align: center; color: #7f8c8d; margin-top: 30px; font-size: 14px; }
    </style>
</head>
<body>
    <div class="container">
        <h1>Country Currency Exchange API</h1>
        <h2>Summary Report</h2>
        
        <div class="stats">
            <strong>Total Countries:</strong> ${totalCountries}<br>
            <strong>Last Refreshed:</strong> ${lastRefreshedAt.toLocaleString()}
        </div>
        
        <h3>Top 5 Countries by Estimated GDP:</h3>
        <div class="country-list">
            ${topCountries
              .map((country, index) => {
                const gdp = country.estimated_gdp
                  ? `$${(country.estimated_gdp / 1e9).toFixed(2)}B`
                  : 'N/A';
                return `<div class="country-item">${index + 1}. ${
                  country.name
                } - ${gdp}</div>`;
              })
              .join('')}
        </div>
        
        <div class="footer">
            Generated by Country Currency Exchange API
        </div>
    </div>
</body>
</html>`;
  }

  private generateTextContent(
    totalCountries: number,
    topCountries: Country[],
    lastRefreshedAt: Date
  ): string {
    let content = `Country Currency Exchange API - Summary Report\n`;
    content += `==============================================\n\n`;
    content += `Total Countries: ${totalCountries}\n`;
    content += `Last Refreshed: ${lastRefreshedAt.toLocaleString()}\n\n`;
    content += `Top 5 Countries by Estimated GDP:\n`;
    content += `--------------------------------\n`;

    topCountries.forEach((country, index) => {
      const gdp = country.estimated_gdp
        ? `$${(country.estimated_gdp / 1e9).toFixed(2)}B`
        : 'N/A';
      content += `${index + 1}. ${country.name} - ${gdp}\n`;
    });

    content += `\nGenerated by Country Currency Exchange API\n`;
    return content;
  }

  getSummaryImagePath(): string {
    return path.join(this.cacheDir, 'summary.png');
  }

  summaryImageExists(): boolean {
    const imagePath = this.getSummaryImagePath();
    return fs.existsSync(imagePath);
  }

  deleteSummaryImage(): void {
    const imagePath = this.getSummaryImagePath();
    if (fs.existsSync(imagePath)) {
      fs.unlinkSync(imagePath);
      logger.info('Summary image deleted');
    }
  }
}

export default new ImageGeneratorService();
